### ISSUE TITLE
All setting lost after exit and start again.

### ISSUE THREAD

**Issue by maidmeow4** [ggrandes/jentunnel#7]
JRE: 8u371 64bit, OS: Windows 10

All the settings were lost after a exit from the tray menu, tried change configuration directory, no luck. (But the theme was preserved, which is weird.)

**Comment by ggrandes** [comment]
Directory permissions?
Missing save icon click?

**Comment by maidmeow4** [comment]
The config dir is placed next to the exe, `D:\jEnTunnel\.config` (drive D is not a system drive, and current user has full control to the dir).
jEnTunnel actually remembers the config dir I specified last time, but all connections I created were gone.

~~About the "save icon" you mentioned, I didn't see one, where is it?~~
Oh shoot I see it, my bad.
